server.port=8080

spring.application.name=API-GATEWAY

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# User Service route
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**

# Product Service route
spring.cloud.gateway.server.webmvc.routes[1].id=product-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/products/**

# Actuator
management.endpoints.web.exposure.include=health,info

# Cart Service
spring.cloud.gateway.server.webmvc.routes[2].id=cart-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://CART-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/cart/**

# Order Service
spring.cloud.gateway.server.webmvc.routes[3].id=order-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.server.webmvc.routes[4].id=payment-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/payments/**

